# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  node-test:
    docker:
      - image: circleci/node:14.16.1
    environment:
      NODE_ENV: test

jobs:
  build:
    executor: node-test

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - run:
          name: Install global packages
          command: sudo yarn global add codecov

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  code-cov:
    executor: node-test

    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Unit Tests with Code Coverage
          command: npm run test:unit:cov

      - run:
          name: Send reports to codecov.io
          command: codecov

workflows:
  main:
    jobs:
      - build
      - code-cov
