version: "3.9"

services:
  db:
    image: timescale/timescaledb:2.2.0-pg13
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - POSTGRES_DB=mapi_db_dev
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"

